---
title: "Talks"
---

1. Make intearctive complex heatmaps, poster presentation on Bioconductor conference 2021. [Poster](https://f1000research.com/posters/10-600).
2. spiralize: an R package for visualizing data on spirals, contributed talk on Bioconductor Asia 2021. [YouTube](https://www.youtube.com/watch?v=o-PxvBnkYoI), [Slides](https://docs.google.com/presentation/d/18tjccfyAuVjt1vhabFxJBdCXvatF7QQq0m691RG-uBc/edit?usp=sharing).
3. On the heaviness of package dependencies, contributed talk on useR! 2022. [Slides](https://docs.google.com/presentation/d/11EwFl18Ana1pZ1C4UDdbdqjLJnbM9F32KOHXRpbY4IM/edit?usp=sharing).
4. cola: a general framework for consensus partitioning, package demo on Bioconductor
conference 2022. [YouTube](https://www.youtube.com/watch?v=gy_m0wFZij0&t=8s). [Slides](https://docs.google.com/presentation/d/1Ggttz6XOLMDnJs-8z6opUSlfH54PCTasi-fNbhL1msY/edit?usp=sharing).
5. simplifyEnrichment: A Bioconductor Package for Clustering and Visualizing Functional
Enrichment Results, package demo on EuroBioc 2022, Heidelberg Germany. [Slides](https://docs.google.com/presentation/d/1A8P8lJLRB3NHf2Uf2qmPgE6_6yhK9dCfX4OrNzRWANI/edit?usp=sharing).
6. Complex Heatmap visualization, invited talk on China Gut conference 2023 (中国肠道大会2023). [Video](https://cs.chinagut.cn/academic/report?agendaCode=d8d080137c2848d285a8a1054711f2e5#sphf).
7. rGREAT: an R/Bioconductor Package for Functional Enrichment on Genomic Regions,
package demo on Bioconductor conference 2023. [Slides](https://docs.google.com/presentation/d/1gza3ntOo2pwI9HiNdypQRk0ARNJ60EiwE1svoyOXJ-o/edit?usp=sharing), [Demo1, local_great.html](local_great.html), [Demo2, online_great.html](online_great.html).
8. On the Dependency Heaviness of CRAN/Bioconductor Ecosystem, short talk on Bioconductor
conference 2023. [Slides](https://docs.google.com/presentation/d/1eVGDdV4FlcpjGONuhRagFUbAqRdahfdC3lmGFtgjkgc/edit?usp=sharing).
9. 组学数据分析和可视化工具开发, [iMeta典型文章系列讲座](https://blog.csdn.net/woodcorpse/article/details/138638507).
10. GHGA Webinar: Biological data visualisation in R and Bioconductor, https://www.ghga.de/events/detail/ghga-webinar-biological-data-visualisation-in-r-and-bioconductor.

