---
title: "Changes in ComplexHeatmap 2.6.0"
date: 2020-10-28
---

```{r, echo = FALSE}
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    warning = FALSE,
    fig.align = "center",
    fig.width = 5,
    fig.height = 5
)
library(GetoptLong)
options(digits = 4)
```


The **ComplexHeatmap** package is still growing. Till now, there are 62
CRAN/Bioconductor packages that depend on ComplexHeatmap where 7 packages are also mine
:). It has approxiamtely [10k downloads per
month](http://bioconductor.org/packages/stats/bioc/ComplexHeatmap/), [600
issues](https://github.com/jokergoo/ComplexHeatmap/issues) on GitHub and
nearly 600 GitHub stars. [The ComplexHeatmap
paper](https://academic.oup.com/bioinformatics/article/32/18/2847/1743594) has
more than 1100 citations. Thank you for liking ComplexHeatmap!

In version 2.6.0 which corresponds to the new Bioconductor release, there are
following major changes that are user-visible:

1. Add a `ComplexHeatmap::pheatmap()` function which is almost compatible to
   `pheatmap::pheatmap()`. It helps users to seamlessly (I hope!) move from
   **pheatmap** to **ComplexHeatmap** to use more unique features in
   **ComplexHeatmap**, e.g. concatenating multiple heatmaps. See the blog post
   ["Translate from pheatmap to
   ComplexHeatmap"](https://jokergoo.github.io/2020/05/06/translate-from-pheatmap-to-complexheatmap/)
   for more details.

2. Support interactive heatmaps. Users can either do it under the interactive
   graphics device or through a shiny app. See the blog post ["Interactive
   ComplexHeatmap"](https://jokergoo.github.io/2020/05/15/interactive-complexheatmap/)
   for more details.

3. Points can be added to the dendrogram nodes. [See examples here](https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#render-dendrograms).

4. Rasterization has been improved and multiple methods for rasterization are
   implemented. Now it supports **magick** package for better rasterization
   and also **ragg** package for writting temporary png image files. See the
   blog post ["Rasterization in
   ComplexHeatmap"](https://jokergoo.github.io/2020/06/30/rasterization-in-complexheatmap/)
   for more details.

5. Positions of column titles has been adjusted, so that it can be perfectly aligned with ggplot2 figures.
   [See examples here](https://twitter.com/jokergoo_gu/status/1318824850748735489).

6. Users can rotate annotation names/labels. [Check examples
   here](https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#annotation-labels).

7. Users can choose how to group legends, which means legends for row annotations
   can be grouped with column annotation legends. [See examples
   here](https://jokergoo.github.io/ComplexHeatmap-reference/book/legends.html#heatmap-and-annotation-legends)
   (check the use of `legend_grouping` argument).

8. `oncoPrint()` now draws legends the same as the graphics defined in `alter_fun`, which means
   users do not need to manually construct legends for complex alteration types. [Check all the
   legends in the oncoPrint chapter](https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html).

