---
title: "Top10 first-authors on Bioinformatics"
date: 2023-07-25
---

```{r, echo = FALSE}
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    warning = FALSE,
    fig.width = 5,
    fig.height = 5,
    fig.align = "center"
)
options("width" = 100)
```

Following code obtains numbers of papers for first-authors on Bioinformatics.

```r
library(pubmedR)

api_key = NULL

# pubmed only allows downloading less than 10k records at a time,
# so I split them into two parts
query = '("Bioinformatics (Oxford, England)"[Journal]) AND (("1998"[Date - Publication] : "2014"[Date - Publication]))'
res <- pmQueryTotalCount(query = query, api_key = api_key)
D1 <- pmApiRequest(query = query, limit = res$total_count, api_key = NULL)

query = '("Bioinformatics (Oxford, England)"[Journal]) AND (("2015"[Date - Publication] : "2023"[Date - Publication]))'
res <- pmQueryTotalCount(query = query, api_key = api_key)
D2 <- pmApiRequest(query = query, limit = res$total_count, api_key = NULL)

m1 = pmApi2df(D1)
m2 = pmApi2df(D2)
m = rbind(m1, m2)

df = df[df$DT == "JOURNAL ARTICLE", ]
```

The top 10 first-authors are:

```r
fa = gsub(";.*$", "", df$AF)
sort(table(fa), decreasing = TRUE)[1:10]
```

```{r, echo = FALSE}
fa = readRDS("pubmed_fa.rds")
sort(table(fa), decreasing = TRUE)[1:10]
```